Change progress bar to spinner
lexmag/dicon pull request #30
Opened 2017-03-20 16:18 UTC by ericmj

2017-03-20 16:19 UTC, ericmj commented on lib/dicon/secure_shell.ex
> +           IO.write(IO.ANSI.format([:clear_line, ?\r])),
This will remove the progress bar after spinner is done. Not sure if we want this but I thought it was kind of neat.

2017-03-27 14:09 UTC, lexmag commented on lib/dicon/secure_shell.ex
> +    IO.ANSI.format([:clear_line, ?\r, spinner, ?\s, Integer.to_string(percent), ?%])
Let's start piping with `[..]` constructing.

2017-04-24 11:13 UTC, lexmag requested changes
One small change and we are good to go.

2017-05-16 12:21 UTC, lexmag approved these changes

2017-05-16 12:22 UTC, merged